# Generated by Django 5.2.13 on 2026-05-30 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0015_configure_overdue_cron'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ASSIGNED', 'Recommandation assignée'), ('DELEGATED', 'Délégation ETP'), ('EVIDENCE_REJECTED', 'Preuves rejetées'), ('EVIDENCE_VALIDATED', 'Preuves validées'), ('CLOSED', 'Recommandation clôturée'), ('EXTENSION_REQUESTED', 'Demande de report soumise'), ('EXTENSION_APPROVED', "Report d'échéance approuvé"), ('EXTENSION_REJECTED', "Report d'échéance rejeté"), ('OVERDUE', 'Passage en retard'), ('OVERDUE_J30', 'Retard ≥ 30 jours'), ('OVERDUE_J60_ESCALATION', 'Escalade retard 60 jours'), ('DUE_SOON_J7', 'Échéance dans 7 jours'), ('DUE_SOON_J3', 'Échéance dans 3 jours')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(help_text='Texte court affiché dans le dropdown.', max_length=200, verbose_name='Titre')),
                ('body', models.TextField(blank=True, default='', help_text='Précision facultative (ex. motif de rejet).', verbose_name='Détail')),
                ('url', models.CharField(blank=True, default='', help_text='URL relative vers laquelle redirige le clic.', max_length=500, verbose_name='Lien')),
                ('is_urgent', models.BooleanField(default=False, help_text='True pour ruptures / escalades (affichage prioritaire).', verbose_name='Urgent')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Lu')),
                ('idempotency_key', models.CharField(help_text="Format : '{TYPE}:{recommendation_pk}[:{extra}]'. Garantit l'unicité — aucun doublon même en cas d'appels répétés.", max_length=255, unique=True, verbose_name="Clé d'idempotence")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créée le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workflow.recommendation', verbose_name='Recommandation')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'), models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_date')],
            },
        ),
    ]
