# Generated by Django 5.2.13 on 2026-05-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ASSIGNED', 'Recommandation assignée'), ('DELEGATED', 'Délégation ETP'), ('EVIDENCE_REJECTED', 'Preuves rejetées'), ('EVIDENCE_VALIDATED', 'Preuves validées'), ('CLOSED', 'Recommandation clôturée'), ('EXTENSION_REQUESTED', 'Demande de report soumise'), ('EXTENSION_APPROVED', "Report d'échéance approuvé"), ('EXTENSION_REJECTED', "Report d'échéance rejeté"), ('EVIDENCE_SUBMITTED', 'Preuves soumises — revue requise'), ('OVERDUE', 'Passage en retard'), ('OVERDUE_J30', 'Retard ≥ 30 jours'), ('OVERDUE_J60_ESCALATION', 'Escalade retard 60 jours'), ('DUE_SOON_J7', 'Échéance dans 7 jours'), ('DUE_SOON_J3', 'Échéance dans 3 jours')], max_length=30, verbose_name='Type'),
        ),
    ]
