# Generated by Django 5.2.13 on 2026-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de l'envoi e-mail (Story 4.3). Null si aucun e-mail n'est parti (type hors whitelist, flag désactivé, destinataire sans adresse). Sert de verrou d'idempotence : une tâche rejouée n'envoie jamais de second e-mail.", null=True, verbose_name='E-mail envoyé le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ASSIGNED', 'Recommandation assignée'), ('DELEGATED', 'Délégation ETP'), ('EVIDENCE_REJECTED', 'Preuves rejetées'), ('EVIDENCE_VALIDATED', 'Preuves validées'), ('CLOSED', 'Recommandation clôturée'), ('EXTENSION_REQUESTED', 'Demande de report soumise'), ('EXTENSION_APPROVED', "Report d'échéance approuvé"), ('EXTENSION_REJECTED', "Report d'échéance rejeté"), ('EVIDENCE_SUBMITTED', 'Preuves soumises — revue requise'), ('OVERDUE', 'Passage en retard'), ('OVERDUE_J30', 'Retard ≥ 30 jours'), ('OVERDUE_J60_ESCALATION', 'Escalade retard 60 jours'), ('DUE_SOON_J7', 'Échéance dans 7 jours'), ('DUE_SOON_J3', 'Échéance dans 3 jours'), ('PROVISIONING_REQUESTED', 'Demande de compte à valider'), ('PROVISIONING_APPROVED', 'Compte approuvé'), ('PROVISIONING_REJECTED', 'Demande de compte rejetée'), ('TAMPER_ALERT', 'Altération de dossier scellé'), ('IMPORT_COMPLETED', 'Import terminé'), ('IMPORT_FAILED', "Échec de l'import"), ('PRIVILEGE_ALERT', 'Modification de privilège'), ('SYSTEM_ALERT', 'Alerte système')], max_length=30, verbose_name='Type'),
        ),
    ]
