repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

#  - repo: https://github.com/Riverside-Healthcare/djLint
#    rev: v1.34.1
#    hooks:
#      # Linter: cherche les erreurs (ex: commentaires multi-lignes invalides)
#      - id: djlint-django
#        args: ["--lint"]
#        files: \.html$
