# Generated by Django 5.2.13 on 2026-04-17 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression (soft)'), ('LOGIN', 'Connexion réussie'), ('LOGIN_FAILED', 'Tentative de connexion échouée'), ('LOGOUT', 'Déconnexion'), ('TRANSITION', 'Transition FSM'), ('SYSTEM', 'Action système'), ('EXPORT', 'Export')], max_length=20, verbose_name='Action')),
                ('content_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'entité")),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('changes', models.JSONField(blank=True, help_text='Format : {champ: [avant, après]}', null=True, verbose_name='Changements')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
