# Generated by Django 5.2.13 on 2026-05-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_user_id_429f6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_action_0c6a84_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_content_997ff9_idx',
        ),
    ]
