# Generated by Django 5.2.13 on 2026-05-29 21:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_add_extension_audit_actions'),
        ('workflow', '0015_configure_overdue_cron'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HmacSeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hmac_hash', models.CharField(help_text='Digest hexadécimal HMAC-SHA256 du dossier scellé.', max_length=64, verbose_name='Empreinte HMAC-SHA256')),
                ('sealed_metadata', models.JSONField(help_text='Snapshot figé des champs métier entrant dans le calcul HMAC.', verbose_name='Métadonnées scellées')),
                ('file_hashes', models.JSONField(default=dict, help_text='{evidence_file_id: sha256_hash} des preuves acceptées.', verbose_name='Hashs des preuves')),
                ('sealed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scellé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hmac_seal', to='workflow.recommendation', verbose_name='Recommandation')),
                ('sealed_by', models.ForeignKey(blank=True, help_text='Auditeur ayant clôturé et scellé le dossier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sealed_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Scellé par')),
            ],
            options={
                'verbose_name': 'Sceau HMAC',
                'verbose_name_plural': 'Sceaux HMAC',
                'db_table': 'audit_hmac_seal',
                'ordering': ['-sealed_at'],
            },
        ),
    ]
