# Generated by Django 5.2.13 on 2026-06-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_backfill_hmac_seals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression (soft)'), ('LOGIN', 'Connexion réussie'), ('LOGIN_FAILED', 'Tentative de connexion échouée'), ('LOGOUT', 'Déconnexion'), ('TRANSITION', 'Transition FSM'), ('SYSTEM', 'Action système'), ('EXPORT', 'Export'), ('EXTENSION_REQUESTED', 'Demande de report soumise'), ('EXTENSION_APPROVED', 'Demande de report approuvée'), ('EXTENSION_REJECTED', 'Demande de report rejetée'), ('IMPORT', 'Import Excel')], max_length=20, verbose_name='Action'),
        ),
    ]
