/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./templates/**/*.html",
    "./**/templates/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        // Primary Palette (Sentinel Brand)
        "sentinel-orange": "#E87722",
        "sentinel-orange-dark": "#C9631A",
        "sentinel-orange-light": "#FFF3EB",
        "sentinel-brown": "#4A2C2A",
        "sentinel-brown-light": "#6B4A3A",
        "sentinel-brown-dark": "#3A1F1A",

        // Semantic Statuses
        "status-in-progress": "#E87722",
        "status-pending": "#D4A843",
        "status-approved": "#2D8B56",
        "status-rejected": "#C93B3B",
        "status-overdue": "#991B1B",
        "status-closed": "#10B981",

        // Surface & Neutrals
        "surface-base": "#FAF7F4",
        "surface-card": "#FFFFFF",
        "surface-warm": "#F5EDE6",
        "border-subtle": "#E8DFD6",
        "text-primary": "#2D1F1E",
        "text-secondary": "#8B7E74",
        "text-muted": "#B5A99E",

        // Stitch Design / Material Design Tokens
        "surface-dim": "#dcd9d9",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#004b72",
        "outline": "#8d7165",
        "on-secondary-container": "#773615",
        "secondary-fixed-dim": "#ffb595",
        "on-surface": "#1c1b1b",
        "primary-fixed-dim": "#ffb595",
        "tertiary-fixed": "#cce5ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#351000",
        "error-container": "#ffdad6",
        "surface-bright": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "outline-variant": "#e1bfb2",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "secondary": "#924b28",
        "background": "#fcf9f8",
        "on-primary-fixed-variant": "#7c2e00",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed-variant": "#743413",
        "surface-container-highest": "#e5e2e1",
        "on-primary-container": "#541d00",
        "surface-variant": "#e5e2e1",
        "surface-container-high": "#eae7e7",
        "on-background": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#009eea",
        "tertiary-fixed-dim": "#91cdff",
        "inverse-primary": "#ffb595",
        "on-surface-variant": "#594137",
        "secondary-fixed": "#ffdbcd",
        "primary-fixed": "#ffdbcd",
        "tertiary": "#006496",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fea279",
        "on-secondary-fixed": "#351000",
        "surface-container": "#f0eded",
        "inverse-surface": "#313030",
        "primary-container": "#f76b1c",
        "surface-tint": "#a23f00",
        "primary": "#a23f00",
        "surface": "#fcf9f8",
        "on-tertiary-container": "#00314d",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#001e31"
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
