# Generated by Django 5.2.13 on 2026-05-14 07:03

import django.db.models.deletion
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_enrich_organigramme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text="Identifiant métier de la recommandation (ex: REC-2026-042). Saisie manuelle par l'auditeur.", max_length=50, unique=True, verbose_name='Référence')),
                ('mission_date', models.DateField(blank=True, help_text="Date à laquelle la mission d'audit a eu lieu.", null=True, verbose_name='Date de la mission')),
                ('mission_label', models.CharField(blank=True, default='', help_text="Nom complet de la mission d'audit (ex: Contrôle KYC Q3 2025).", max_length=255, verbose_name='Libellé de la mission')),
                ('observations', models.TextField(blank=True, default='', help_text="Constats et observations issus de la mission d'audit.", verbose_name='Observations')),
                ('anomalous_dossiers', models.TextField(blank=True, default='', help_text='Description des dossiers présentant des anomalies.', verbose_name='Dossiers en anomalies')),
                ('description', models.TextField(help_text='Le texte prescriptif de la recommandation. Décrit ce qui doit être corrigé ou amélioré.', verbose_name='Texte de la recommandation')),
                ('source', models.CharField(choices=[('INTERNE', 'Audit Interne'), ('COBAC', 'COBAC'), ('CAC', 'CAC'), ('ANIF', 'ANIF'), ('BEAC', 'BEAC'), ('ANTIC', 'ANTIC'), ('CONSULTANT', 'Consultant')], help_text='Origine réglementaire de la recommandation.', max_length=20, verbose_name='Source')),
                ('priority', models.CharField(choices=[('CRITIQUE', 'Critique'), ('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible')], help_text='Conditionne la couleur UI et la fréquence des relances.', max_length=10, verbose_name='Criticité')),
                ('due_date', models.DateField(help_text='Date limite pour la résolution de la recommandation.', verbose_name='Date de mise en œuvre')),
                ('original_due_date', models.DateField(help_text='Préservée intacte même après un report approuvé. Base du calcul de vieillissement (aging) pour les rapports COBAC.', verbose_name="Date d'échéance originale")),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Brouillon'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('PENDING_DM_REVIEW', 'Validation DM'), ('PENDING_AUDIT_REVIEW', 'Validation Audit'), ('CLOSED_RESOLVED', 'Clôturée')], default='DRAFT', help_text='Piloté par django-fsm. Ne pas modifier directement.', max_length=30, protected=True, verbose_name='Statut FSM')),
                ('is_overdue', models.BooleanField(default=False, help_text='Flag calculé par le scheduler nocturne Django-Q2.', verbose_name='En retard')),
                ('import_tag', models.CharField(blank=True, help_text="Valeur 'IMPORTED' inaltérable si import historique (FR9).", max_length=10, null=True, verbose_name="Tag d'import")),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete — FR6. Possible uniquement en état DRAFT.', verbose_name='Supprimé (soft)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Horodatage du soft delete.', null=True, verbose_name='Date de suppression')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('assigned_dm', models.ForeignKey(blank=True, help_text='Directeur Métier responsable. Renseigné en Story 2.5.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='DM assigné')),
                ('assigned_etp', models.ForeignKey(blank=True, help_text='Employé Traitant exécutant. Renseigné en Story 3.2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='ETP délégué')),
                ('controlled_department', models.ForeignKey(blank=True, help_text='La direction qui a été auditée lors de la mission. Peut différer de la direction concernée par la recommandation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controlled_recommendations', to='users.department', verbose_name='Direction contrôlée')),
                ('created_by', models.ForeignKey(help_text='Auditeur ayant créé la recommandation.', on_delete=django.db.models.deletion.PROTECT, related_name='created_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('department', models.ForeignKey(blank=True, help_text='Direction organisationnelle qui doit implémenter la recommandation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='users.department', verbose_name='Direction concernée')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Ex: Procédure KYC mise à jour, Formation des agents.', max_length=255, verbose_name='Intitulé du livrable')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position du livrable dans la checklist.', verbose_name="Ordre d'affichage")),
                ('is_completed', models.BooleanField(default=False, help_text="Coché par l'opérationnel (ETP/DM) quand le livrable est terminé.", verbose_name='Terminé')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Horodatage automatique lors du cochage.', null=True, verbose_name='Date de complétion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('completed_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant marqué le livrable comme terminé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deliverables', to=settings.AUTH_USER_MODEL, verbose_name='Complété par')),
                ('recommendation', models.ForeignKey(help_text='Recommandation parente à laquelle ce livrable est rattaché.', on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='workflow.recommendation', verbose_name='Recommandation')),
            ],
            options={
                'verbose_name': 'Livrable',
                'verbose_name_plural': 'Livrables',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['status'], name='idx_reco_status'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['created_by'], name='idx_reco_created_by'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['assigned_dm'], name='idx_reco_assigned_dm'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['department'], name='idx_reco_department'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_overdue'], name='idx_reco_overdue'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['priority'], name='idx_reco_priority'),
        ),
    ]
