# Generated by Django 5.2.13 on 2026-05-20 19:32

import apps.workflow.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text="Explication de l'ETP sur les actions menées pour résoudre la recommandation.", verbose_name='Commentaire de résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_submissions', to='workflow.recommendation', verbose_name='Recommandation')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
            ],
            options={
                'verbose_name': 'Soumission de preuves',
                'verbose_name_plural': 'Soumissions de preuves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.workflow.models._evidence_upload_path, verbose_name='Fichier')),
                ('original_filename', models.CharField(help_text="Nom du fichier tel que fourni par l'utilisateur.", max_length=255, verbose_name='Nom original')),
                ('file_size', models.PositiveIntegerField(help_text='Taille du fichier en octets au moment du dépôt.', verbose_name='Taille (octets)')),
                ('mime_type', models.CharField(help_text="Type MIME détecté depuis les magic bytes, pas l'extension.", max_length=100, verbose_name='Type MIME')),
                ('sha256_hash', models.CharField(help_text="Empreinte intègre du fichier pour vérification d'intégrité.", max_length=64, verbose_name='Hash SHA-256')),
                ('tag', models.CharField(choices=[('JUSTIFICATIF', 'Justificatif'), ('PV_RECETTE', 'PV de recette'), ('RAPPORT', 'Rapport'), ('AUTRE', 'Autre')], default='JUSTIFICATIF', max_length=20, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Déposé le')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence_files', to=settings.AUTH_USER_MODEL, verbose_name='Déposé par')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workflow.evidencesubmission', verbose_name='Soumission')),
            ],
            options={
                'verbose_name': 'Fichier probatoire',
                'verbose_name_plural': 'Fichiers probatoires',
                'ordering': ['created_at'],
            },
        ),
    ]
