# Generated by Django 5.2.13 on 2026-05-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_add_evidence_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de validation'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée')], default='PENDING', help_text='Piloté par le DM (Story 3.4). Défaut PENDING à la soumission.', max_length=20, verbose_name='Statut'),
        ),
    ]
