# Generated by Django 5.2.13 on 2026-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_configure_cleanup_cron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencesubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
    ]
