# Generated by Django 5.2.13 on 2026-05-22 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_evidencesubmission_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['submission', 'tag'], name='workflow_ev_submiss_d8415b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesubmission',
            index=models.Index(fields=['recommendation', 'status'], name='workflow_ev_recomme_0a87ac_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencesubmission',
            index=models.Index(fields=['submitted_by', 'status'], name='workflow_ev_submitt_d8cd6a_idx'),
        ),
    ]
