# Generated by Django 5.2.13 on 2026-05-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_evidence_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencesubmission',
            name='review_comment',
            field=models.TextField(blank=True, default='', help_text='Motif saisi par le DM lors du rejet (Story 3.4 — AC2).', verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Horodatage du rejet par le DM.', null=True, verbose_name='Rejeté le'),
        ),
        migrations.AddField(
            model_name='evidencesubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='DM qui a rejeté la soumission. Dénormalisé pour requêtes analytiques rapides sans JOIN sur AuditLog (Story 3.4 — L2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Rejeté par'),
        ),
    ]
