# Generated by Django 5.2.13 on 2026-05-24 04:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_add_rejection_fields_to_evidence_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField(help_text='Date proposée par le demandeur pour la nouvelle échéance.', verbose_name='Nouvelle date souhaitée')),
                ('reason', models.TextField(help_text='Justification obligatoire de la demande de report.', max_length=2000, verbose_name='Motif de la demande')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Statué le')),
                ('audit_comment', models.TextField(blank=True, default='', help_text="Optionnel lors de l'approbation. Obligatoire lors du rejet (AC5).", max_length=2000, verbose_name='Commentaire Audit')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='workflow.recommendation', verbose_name='Recommandation')),
                ('requested_by', models.ForeignKey(help_text='DM ou DG personnellement assigné ayant soumis la demande.', on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Auditeur ayant approuvé ou rejeté la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Statué par')),
            ],
            options={
                'verbose_name': 'Demande de report',
                'verbose_name_plural': 'Demandes de report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recommendation', 'status'], name='idx_ext_req_reco_status')],
            },
        ),
    ]
