# Generated by Django 5.2.13 on 2026-05-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_finalize_source_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='source',
            field=models.ForeignKey(help_text='Origine réglementaire de la recommandation.', on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='workflow.recommendationsource', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='recommendationsource',
            name='code',
            field=models.CharField(help_text='Identifiant technique immuable (ex: COBAC). Ne peut plus être modifié après création.', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='recommendationsource',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Sources inactives masquées du formulaire de création. Désactiver plutôt que supprimer pour préserver l'historique.", verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='recommendationsource',
            name='is_external',
            field=models.BooleanField(default=True, help_text='True = autorité réglementaire externe (COBAC, ANIF…). False = audit interne.', verbose_name='Source externe'),
        ),
    ]
