# Generated by Django 5.2.13 on 2026-06-13 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_repoint_nightly_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(blank=True, help_text='Fichier Excel original archivé pour traçabilité réglementaire (COBAC).', null=True, upload_to='imports/', verbose_name='Fichier source')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Importé le')),
                ('recommendation_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de recommandations')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'verbose_name': "Lot d'import",
                'verbose_name_plural': "Lots d'import",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text="Lot d'import auquel appartient cette recommandation (Story 6.5 — FR7).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='workflow.importbatch', verbose_name="Lot d'import"),
        ),
    ]
