# Generated by Django 5.2.13 on 2026-04-24 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_audit_admin',
            field=models.BooleanField(default=False, help_text="Flag du Directeur de l'Audit Interne ou de ses délégués (ADR-10). Permet d'attribuer les rôles métiers et les habilitations aux comptes « coquilles vides » via l'interface dédiée (FR36).", verbose_name='Administrateur Audit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_external',
            field=models.BooleanField(default=False, help_text="Réservé aux auditeurs externes (COBAC/BEAC/CAC). Limite l'accès au périmètre de mission uniquement (Story 1.3).", verbose_name='Compte externe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('AUDIT', 'Audit Interne'), ('DM', 'Directeur Métier'), ('ETP', 'Employé Traitant'), ('DG', 'Direction Générale'), ('EXT', 'Auditeur Externe'), ('RSSI', 'RSSI / Support IT')], default='', help_text="Rôle métier Sentinel. Vide = compte « coquille vide » en attente d'activation par l'Audit Interne (ADR-10, FR37).", max_length=10, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom complet du département (ex: Direction des Opérations).', max_length=100, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code court unique (ex: DOP). Utilisé dans les filtres et les exports pour identifier rapidement le département.', max_length=10, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('DIRECTION', 'Direction'), ('AGENCE', 'Agence'), ('FILIALE', 'Filiale')], help_text="Catégorie structurelle dans l'organigramme BICEC.", max_length=20, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, help_text="Désactiver plutôt que supprimer pour préserver l'intégrité des données historiques.", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('parent', models.ForeignKey(blank=True, help_text='Département hiérarchiquement supérieur. NULL pour les entités racines (Directions principales).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.department', verbose_name='Département parent')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Département de rattachement. Détermine le périmètre RBAC de visibilité des données (FR28).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.department', verbose_name='Département'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_user_role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department'], name='idx_user_dept'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent'], name='idx_dept_parent'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['type'], name='idx_dept_type'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='idx_dept_code'),
        ),
    ]
