# Generated by Django 5.2.13 on 2026-05-02 23:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_user_enrich'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(help_text="Institution d'origine de l'auditeur (ex: COBAC, BEAC, CAC).", max_length=100, verbose_name='Organisation')),
                ('scope_description', models.TextField(blank=True, default='', help_text="Description libre du périmètre d'intervention (ex: Audit des procédures de crédit).", verbose_name='Périmètre de la mission')),
                ('start_date', models.DateField(help_text="Date de début de la mission d'audit externe.", verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text="Date de fin prévue. Peut être NULL si la durée n'est pas encore définie.", null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la mission est en cours. Désactiver en fin de mission plutôt que supprimer.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('auditor', models.ForeignKey(help_text='Utilisateur externe (is_external=True) rattaché à cette mission.', on_delete=django.db.models.deletion.PROTECT, related_name='external_missions', to=settings.AUTH_USER_MODEL, verbose_name='Auditeur externe')),
            ],
            options={
                'verbose_name': 'Mission externe',
                'verbose_name_plural': 'Missions externes',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['auditor'], name='idx_extmission_auditor'), models.Index(fields=['organization'], name='idx_extmission_org'), models.Index(fields=['is_active'], name='idx_extmission_active')],
            },
        ),
    ]
