# Generated by Django 5.2.13 on 2026-05-04 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_rssi_to_admin(apps, schema_editor):
    """Convertit les utilisateurs avec role='RSSI' en role='ADMIN'."""
    User = apps.get_model("users", "User")
    User.objects.filter(role="RSSI").update(role="ADMIN")


# Note : La reverse migration originale (ADMIN→RSSI) a été retirée car
# des comptes ADMIN ont été créés après cette migration. Un rollback
# aveugle corromprait ces données. Voir analyse CodeRabbit #6.


def migrate_filiale_to_direction(apps, schema_editor):
    """Convertit les départements FILIALE en DIRECTION (type supprimé)."""
    Department = apps.get_model("users", "Department")
    Department.objects.filter(type="FILIALE").update(type="DIRECTION")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_external_mission'),
    ]

    operations = [
        # --- Data migration AVANT le changement de choices ---
        migrations.RunPython(migrate_rssi_to_admin, migrations.RunPython.noop),
        migrations.RunPython(migrate_filiale_to_direction, noop),
        # --- Schema changes ---
        migrations.AlterField(
            model_name='department',
            name='type',
            field=models.CharField(choices=[('DG', 'Direction Générale'), ('DIRECTION', 'Direction'), ('SOUS_DIRECTION', 'Sous-Direction'), ('DEPARTEMENT', 'Département'), ('SERVICE', 'Service'), ('REGION', 'Direction Régionale'), ('AGENCE', 'Agence')], help_text="Catégorie structurelle dans l'organigramme BICEC.", max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='externalmission',
            name='auditor',
            field=models.ForeignKey(help_text='Utilisateur externe (is_external=True) rattaché à cette mission.', limit_choices_to={'is_external': True, 'role': 'EXT'}, on_delete=django.db.models.deletion.PROTECT, related_name='external_missions', to=settings.AUTH_USER_MODEL, verbose_name='Auditeur externe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('AUDIT', 'Audit Interne'), ('DM', 'Directeur Métier'), ('ETP', 'Employé Traitant'), ('DG', 'Direction Générale'), ('EXT', 'Auditeur Externe'), ('ADMIN', 'Admin')], default='', help_text="Rôle métier Sentinel. Vide = compte « coquille vide » en attente d'activation par l'Audit Interne (ADR-10, FR37).", max_length=10, verbose_name='Rôle'),
        ),
    ]

