# Generated by Django 5.2.13 on 2026-06-06 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_finalize_org_unit_type_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProvisioningRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_username', models.CharField(help_text='Login de connexion du futur compte.', max_length=150, verbose_name='Identifiant')),
                ('requested_first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Prénom')),
                ('requested_last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nom')),
                ('requested_email', models.EmailField(help_text='Adresse e-mail professionnelle du futur compte.', max_length=254, verbose_name='E-mail')),
                ('hashed_initial_password', models.CharField(help_text="Hash Django du mot de passe initial saisi par l'Admin IT. Transféré tel quel au User lors de l'approbation.", max_length=128, verbose_name='Mot de passe initial (haché)')),
                ('requested_role', models.CharField(choices=[('AUDIT', 'Audit Interne'), ('DM', 'Directeur Métier'), ('ETP', 'Employé Traitant'), ('DG', 'Direction Générale'), ('EXT', 'Auditeur Externe'), ('ADMIN', 'Admin')], help_text="Rôle métier à attribuer au compte lors de l'approbation.", max_length=10, verbose_name='Rôle')),
                ('mission_organization', models.CharField(blank=True, default='', help_text="Organisation d'origine de l'auditeur externe (ex. COBAC, BEAC). Requis si le rôle est EXT.", max_length=100, verbose_name='Organisation (auditeur externe)')),
                ('mission_scope', models.TextField(blank=True, default='', help_text="Description libre du périmètre d'intervention de la mission.", verbose_name='Périmètre de la mission')),
                ('mission_start_date', models.DateField(blank=True, help_text='Requis si le rôle est EXT.', null=True, verbose_name='Date de début de mission')),
                ('mission_end_date', models.DateField(blank=True, help_text='Optionnel — peut être laissé vide si la durée est indéterminée.', null=True, verbose_name='Date de fin de mission')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=10, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Obligatoire en cas de rejet. Laissé vide sinon.', verbose_name='Motif du rejet')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('requested_by', models.ForeignKey(help_text='Admin IT (maker) qui a soumis la demande.', on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('requested_department', models.ForeignKey(blank=True, help_text='Département de rattachement. Optionnel pour AUDIT, ADMIN et EXT.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='users.department', verbose_name='Département')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Membre du groupe « Administrateurs Sentinel » (checker).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Demande de provisioning',
                'verbose_name_plural': 'Demandes de provisioning',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_provreq_status'), models.Index(fields=['requested_by'], name='idx_provreq_maker')],
            },
        ),
    ]
