# Generated by Django 5.2.13 on 2026-06-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_create_approvers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_system',
            field=models.BooleanField(default=False, editable=False, help_text="Entité technique seedée à l'installation (héberge les administrateurs Sentinel). Renommable, mais ni supprimable ni désactivable.", verbose_name='Entité système'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='', help_text="Titre officiel affiché (ex : Directeur de l'Audit Interne). Purement informatif — aucun impact sur les rôles ni les permissions.", max_length=100, verbose_name='Fonction / Poste'),
        ),
        migrations.AddField(
            model_name='userprovisioningrequest',
            name='requested_is_audit_admin',
            field=models.BooleanField(default=False, help_text="Positionne is_audit_admin=True sur le compte créé (profil « Directeur de l'Audit »). Valide uniquement si le rôle est AUDIT.", verbose_name='Administrateur Audit demandé'),
        ),
        migrations.AddField(
            model_name='userprovisioningrequest',
            name='requested_job_title',
            field=models.CharField(blank=True, default='', help_text='Titre officiel à affecter au compte (purement informatif).', max_length=100, verbose_name='Fonction demandée'),
        ),
        migrations.AddField(
            model_name='userprovisioningrequest',
            name='requested_profile',
            field=models.CharField(blank=True, default='', help_text="Clé du profil (ACCOUNT_TEMPLATES) sélectionné par le Maker. Trace l'intention métier dans l'audit trail.", max_length=30, verbose_name='Profil de création utilisé'),
        ),
    ]
