# Generated by Django 5.2.13 on 2026-06-14 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_seed_admin_org_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprovisioningrequest',
            name='request_type',
            field=models.CharField(choices=[('CREATE', 'Création'), ('MODIFY', 'Modification')], db_index=True, default='CREATE', max_length=10, verbose_name='Type de demande'),
        ),
        migrations.AddField(
            model_name='userprovisioningrequest',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Rempli uniquement pour les demandes de modification de profil.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur cible'),
        ),
        migrations.AlterField(
            model_name='userprovisioningrequest',
            name='hashed_initial_password',
            field=models.CharField(blank=True, default='', help_text="Hash Django du mot de passe initial saisi par l'Admin IT. Transféré tel quel au User lors de l'approbation. Vide pour request_type=MODIFY.", max_length=128, verbose_name='Mot de passe initial (haché)'),
        ),
    ]
