# Generated by Django 5.2.13 on 2026-06-19 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_provisioning_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprovisioningrequest',
            name='mission_end_date',
        ),
        migrations.RemoveField(
            model_name='userprovisioningrequest',
            name='mission_organization',
        ),
        migrations.RemoveField(
            model_name='userprovisioningrequest',
            name='mission_scope',
        ),
        migrations.RemoveField(
            model_name='userprovisioningrequest',
            name='mission_start_date',
        ),
    ]
