# Generated by Django 5.2.13 on 2026-06-19 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_userprovisioningrequest_mission_end_date_and_more'),
        ('workflow', '0017_importbatch_and_import_action'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='externalmission',
            name='idx_extmission_auditor',
        ),
        migrations.RemoveIndex(
            model_name='externalmission',
            name='idx_extmission_org',
        ),
        migrations.RemoveIndex(
            model_name='externalmission',
            name='idx_extmission_active',
        ),
        migrations.RemoveField(
            model_name='externalmission',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='externalmission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='externalmission',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text="Membre ayant validé l'ouverture de la mission.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_external_missions', to=settings.AUTH_USER_MODEL, verbose_name='Approuvée par'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='auditors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EXT'}, related_name='external_missions', to=settings.AUTH_USER_MODEL, verbose_name='Auditeurs externes'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='created_by',
            field=models.ForeignKey(help_text="Membre de l'Audit Interne ayant créé la mission.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_external_missions', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='name',
            field=models.CharField(default='Mission', help_text='Nom humain de la campagne (ex: Contrôle COBAC 2026).', max_length=200, verbose_name='Nom de la mission'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='external_missions', to='workflow.recommendation', verbose_name='Recommandations'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='status',
            field=models.CharField(choices=[('PREPARATION', 'En préparation'), ('ACTIVE', 'Active'), ('CLOSED', 'Clôturée')], default='PREPARATION', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='externalmission',
            name='type',
            field=models.CharField(choices=[('COBAC', 'COBAC'), ('CAC', 'CAC'), ('INSPECTION_GROUPE', 'Inspection Groupe'), ('CONSULTANT', 'Consultant')], default='COBAC', max_length=50, verbose_name='Type de mission'),
        ),
        migrations.AlterField(
            model_name='externalmission',
            name='organization',
            field=models.CharField(blank=True, default='', help_text="Institution d'origine de l'auditeur (ex: COBAC, BEAC, CAC).", max_length=100, verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='externalmission',
            index=models.Index(fields=['status'], name='idx_extmission_status'),
        ),
        migrations.AddIndex(
            model_name='externalmission',
            index=models.Index(fields=['type'], name='idx_extmission_type'),
        ),
    ]
