# Generated by Django 5.2.13 on 2026-06-20 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_externalmission_idx_extmission_auditor_and_more'),
        ('workflow', '0017_importbatch_and_import_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmission',
            name='type',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_external': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_missions', to='workflow.recommendationsource', verbose_name='Type de mission'),
        ),
    ]
