# Generated by Django 5.2.13 on 2026-06-20 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_externalmission_type_fk_to_recommendationsource'),
        ('workflow', '0017_importbatch_and_import_action'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='externalmission',
            name='idx_extmission_type',
        ),
        migrations.RemoveField(
            model_name='externalmission',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='externalmission',
            name='type',
        ),
        migrations.AddField(
            model_name='externalmission',
            name='organisation',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_external': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_missions', to='workflow.recommendationsource', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='externalmission',
            index=models.Index(fields=['organisation'], name='idx_extmission_organisation'),
        ),
    ]
