# Generated by Django 5.2.13 on 2026-07-01 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_type_to_organisation_drop_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAdminDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_until', models.DateField(verbose_name="Valide jusqu'au")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Révoquée le')),
                ('delegated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Délégant')),
                ('delegated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Révoquée par')),
            ],
            options={
                'verbose_name': 'Délégation admin audit',
                'verbose_name_plural': 'Délégations admin audit',
                'ordering': ['-created_at'],
            },
        ),
    ]
